services:
  postgres:
    image: postgres:16
    container_name: saas_postgres
    restart: always
    env_file:
      - C:\Repositories\public\saas-platform\.env
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: saas_redis
    restart: always
    ports:
      - '6382:6379'

volumes:
  pgdata:
